{
  "openapi": "3.1.0",
  "x-stoplight": {
    "id": "fkwm2uq8ac6ji"
  },
  "info": {
    "title": "naiveart",
    "version": "1.0",
    "contact": {
      "name": "Alena G",
      "url": "https://alena.example.com",
      "email": "alena.guillaume4@gmail.com"
    },
    "termsOfService": "https://alena.example.com/termsofuse",
    "license": {
      "name": "MIT Licence",
      "url": "https://mit-license.org/"
    },
    "summary": "API for an art gallery",
    "description": "Learning project: API for managing a Naive Art gallery and shop"
  },
  "servers": [
    {
      "url": "https://loutre.stoplight.io"
    }
  ],
  "paths": {
    "/users/{userId}": {
      "parameters": [
        {
          "schema": {
            "type": "integer"
          },
          "name": "userId",
          "in": "path",
          "required": true,
          "description": "Id of an existing user."
        }
      ],
      "get": {
        "summary": "Get User Info by User ID",
        "tags": [],
        "responses": {
          "200": {
            "description": "User Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "Get User Alice Smith": {
                    "value": {
                      "id": 142,
                      "firstName": "Alice",
                      "lastName": "Smith",
                      "email": "alice.smith@gmail.com",
                      "dateOfBirth": "1997-10-31",
                      "emailVerified": true,
                      "signUpDate": "2019-08-24"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User Not Found"
          }
        },
        "operationId": "get-users-userId",
        "description": "Retrieve the information of the user with the matching user ID."
      },
      "patch": {
        "summary": "Update User Information",
        "operationId": "patch-users-userId",
        "responses": {
          "200": {
            "description": "User Updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "Updated User Rebecca Baker": {
                    "value": {
                      "id": 13,
                      "firstName": "Rebecca",
                      "lastName": "Baker",
                      "email": "rebecca@gmail.com",
                      "dateOfBirth": "1985-10-02",
                      "emailVerified": false,
                      "createDate": "2019-08-24"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User Not Found"
          },
          "409": {
            "description": "Email Already Taken"
          }
        },
        "description": "Update the information of an existing user.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string",
                    "description": "If a new email is given, the user's email verified property will be set to false."
                  },
                  "dateOfBirth": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "Update First Name": {
                  "value": {
                    "firstName": "Rebecca"
                  }
                },
                "Update Email": {
                  "value": {
                    "email": "rebecca@gmail.com"
                  }
                },
                "Update Last Name & Date of Birth": {
                  "value": {
                    "lastName": "Baker",
                    "dateOfBirth": "1985-10-02"
                  }
                }
              }
            }
          },
          "description": "Patch user properties to update."
        }
      }
    },
    "/user": {
      "post": {
        "summary": "Create New User",
        "operationId": "post-user",
        "responses": {
          "200": {
            "description": "User Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "New User Bob Fellow": {
                    "value": {
                      "id": 12,
                      "firstName": "Bob",
                      "lastName": "Fellow",
                      "email": "bob.fellow@gmail.com",
                      "dateOfBirth": "1996-08-24",
                      "emailVerified": false,
                      "createDate": "2020-11-18"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Missing Required Information"
          },
          "409": {
            "description": "Email Already Taken"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "dateOfBirth": {
                    "type": "string",
                    "format": "date"
                  }
                },
                "required": [
                  "firstName",
                  "lastName",
                  "email",
                  "dateOfBirth"
                ]
              },
              "examples": {
                "Create User Bob Fellow": {
                  "value": {
                    "firstName": "Bob",
                    "lastName": "Fellow",
                    "email": "bob.fellow@gmail.com",
                    "dateOfBirth": "1996-08-24"
                  }
                }
              }
            }
          },
          "description": "Post the necessary fields for the API to create a new user."
        },
        "description": "Create a new user."
      }
    },
    "/artworks": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {},
        "operationId": "get-artworks",
        "description": "List of all artworks"
      },
      "post": {
        "summary": "",
        "operationId": "post-artworks",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "description": "Add a new artwork"
      }
    },
    "/artworks/{artworkId}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "artworkId",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {},
        "operationId": "get-artworks-artworkId",
        "description": "Get one specifique artwork"
      },
      "put": {
        "summary": "",
        "operationId": "put-artworks-artworkId",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "description": "Update one specifique artwork"
      },
      "delete": {
        "summary": "",
        "operationId": "delete-artworks-artworkId",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "description": "Remove one specifique artwork"
      }
    },
    "/artists": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {},
        "operationId": "get-artists",
        "description": "List of all artists"
      },
      "post": {
        "summary": "",
        "operationId": "post-artists",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "description": "Add a new artist"
      }
    },
    "/artists/{artistId}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "artistId",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {},
        "operationId": "get-artists-artistId",
        "description": "Get one specifique artist"
      },
      "put": {
        "summary": "",
        "operationId": "put-artists-artistId",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "description": "Update one specifique artist"
      },
      "delete": {
        "summary": "",
        "operationId": "delete-artists-artistId",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "description": "Delete one specifique artist"
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "title": "User",
        "type": "object",
        "description": "single user",
        "examples": [
          {
            "id": 142,
            "firstName": "Alice",
            "lastName": "Smith",
            "email": "alice.smith@gmail.com",
            "dateOfBirth": "1997-10-31",
            "emailVerified": true,
            "signUpDate": "2019-08-24"
          }
        ],
        "properties": {
          "id": {
            "type": "integer",
            "description": "Unique identifier for the given user."
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "dateOfBirth": {
            "type": "string",
            "format": "date",
            "example": "1997-10-31"
          },
          "emailVerified": {
            "type": "boolean",
            "description": "Set to true if the user's email has been verified."
          },
          "createDate": {
            "type": "string",
            "format": "date",
            "description": "The date that the user was created."
          }
        },
        "required": [
          "id",
          "firstName",
          "lastName",
          "email",
          "emailVerified"
        ]
      },
      "Artist": {
        "title": "Artist",
        "x-stoplight": {
          "id": "w5ecoemtt8d8l"
        },
        "type": "object",
        "description": "Single artist",
        "properties": {
          "id": {
            "type": "integer"
          },
          "lastName": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "bio": {
            "type": "string"
          },
          "image": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "lastName"
        ]
      },
      "Artwork": {
        "title": "Artwork",
        "x-stoplight": {
          "id": "rqhy79eathxml"
        },
        "type": "object",
        "description": "Single artwork",
        "properties": {
          "id": {
            "type": "integer"
          },
          "title": {
            "type": "string"
          },
          "artist": {
            "allOf": [
              {
                "properties": {
                  "artistId": {
                    "type": "integer"
                  },
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "bio": {
                    "type": "string"
                  },
                  "artistImage": {
                    "type": "string"
                  }
                },
                "required": [
                  "lastName"
                ]
              }
            ],
            "type": "object"
          },
          "created": {
            "type": "string",
            "format": "date"
          },
          "description": {
            "type": "string"
          },
          "techniques": {
            "type": "string"
          },
          "dimensions": {
            "type": "string"
          },
          "price": {
            "type": "number",
            "minimum": 0
          },
          "available": {
            "type": "boolean"
          },
          "onSale": {
            "type": "boolean"
          },
          "image": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "title",
          "artist",
          "available"
        ]
      }
    },
    "securitySchemes": {
      "API Key": {
        "name": "apikey",
        "type": "apiKey",
        "in": "query"
      }
    }
  }
}